[project]
name = "verifiers"
authors = [
    {name = "William Brown", email = "williambrown97@gmail.com"},
]
version = "0.1.0"
description = "Verifiers for reinforcement learning with LLMs"
license = "MIT"
license-file = "LICENSE"
requires-python = ">=3.11"
dependencies = [
    "datasets",
    "liger-kernel",
    "transformers",
    "vllm",
    "trl @ git+https://github.com/willccbb/trl.git@grpo-envs",
]