[project]
name = "verifiers"
authors = [
    {name = "William Brown", email = "williambrown97@gmail.com"},
]
version = "0.1.0"
description = "Verifiers for reinforcement learning with LLMs"
requires-python = ">=3.11"
dependencies = [
    "trl @ git+https://github.com/willccbb/trl.git@grpo-envs",
    "liger-kernel",
    "deepspeed",
    "vllm"
]