[project]
name = "verifiers"
authors = [
    {name = "William Brown", email = "williambrown97@gmail.com"},
]
version = "0.0.0"
description = "Verifiers for reinforcement learning with LLMs"
requires-python = ">=3.11"
dependencies = [
    "vllm",
    "torch",
    "transformers",
    "datasets",
    "trl"
]
