[project]
name = "vf-search-r1"
version = "0.1.0"
dependencies = [
    "datasets>=4.0.0",
    "requests>=2.32.4",
    "ruff>=0.12.7",
    "verifiers>=0.1.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_search_r1.py"]
